main:
  - name: æ²Ÿé€š
    identifier: communication
    weight: 100
    url: https://sivasub.com/
    params:
      header: é€šè¿‡å„ç§å¹³å°ä¸æˆ‘è”ç³»ã€‚
      icon:
        vendor: font-awesome-solid
        name: comments

  - name: æ–‡æ¡£
    identifier: communication-docs
    parent: communication
    url: https://sivasub.com/
    weight: 1
    params:
      icon:
        vendor: bs
        name: book
      description: ä½¿ç”¨æ–‡æ¡£ã€‚

  - name: GitHub
    parent: communication
    url: https://github.com/siva-sub
    weight: 2
    params:
      icon:
        vendor: fab
        name: github
      description: ä»£ç ä»“åº“ã€‚

  - name: LinkedIn
    parent: communication
    url: https://www.linkedin.com/in/sivasub987/
    weight: 3
    params:
      icon:
        vendor: fab
        name: linkedin
        color: #0077b5
      description: åœ¨ LinkedIn ä¸Šä¸æˆ‘è”ç³»ã€‚

  - name: Gmail
    parent: communication
    url: mailto:Sivasub987@gmail.com
    weight: 4
    params:
      icon:
        vendor: font-awesome-solid
        name: envelope
        color: #D44638
      description: ç»™æˆ‘å‘é€ç”µå­é‚®ä»¶ã€‚

  - name: WhatsApp
    parent: communication
    url: https://api.whatsapp.com/send?phone=6598272558&text=Hi%20Siva%20ğŸ‘‹%2C%20I%20saw%20your%20profile%20and%20wanted%20to%20connect%20with%20you.
    weight: 5
    params:
      icon:
        vendor: font-awesome-brands
        name: whatsapp
        color: green
      description: åœ¨ WhatsApp ä¸Šä¸æˆ‘è”ç³»ã€‚
